"""add_ground_truth_label

Revision ID: 563e6d30f955
Revises: 4185da0ca3a3
Create Date: 2026-10-03 21:05:15.975175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563e6d30f955'
down_revision: Union[str, Sequence[str], None] = '4185da0ca3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ground_truth_label', sa.String(length=50), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ground_truth_label', sa.String(length=50), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ground_truth_label', sa.String(length=50), nullable=True))

    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ground_truth_label', sa.String(length=50), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ground_truth_label', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('ground_truth_label')

    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.drop_column('ground_truth_label')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('ground_truth_label')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('ground_truth_label')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('ground_truth_label')

    # ### end Alembic commands ###
